name:                aern2-affarith
version:             0.2.15.0
github:              "michalkonecny/aern2"
license:             BSD3
author:              "Michal Konecny"
maintainer:          "mikkonecny@gmail.com"
copyright:           "2024 Michal Konecny"

# extra-source-files:
# - README.md
# - changelog.md

# Metadata used when publishing your package
synopsis:            Arbitrary precision affine arithmetic
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michalkonecny/aern2/#readme>

dependencies:
- base == 4.*
- containers
- hashable
- hspec
- QuickCheck
- collect-errors >= 0.1.5
- mixed-types-num >= 0.5.11
- cdar-mBound >= 0.1.0.0
- aern2-mp >= 0.2.15

default-extensions:
- GHC2021
- RebindableSyntax
- DuplicateRecordFields
- OverloadedRecordDot
- TypeFamilies

library:
  source-dirs: src
  ghc-options:
  - -O2 -Wall
  - -Wno-orphans

tests:
  aern2-affarith-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aern2-affarith
