name:                aern2-net
version:             0.2.0.0
github:              "michalkonecny/aern2"
license:             BSD3
author:              "Michal Konecny"
maintainer:          "mikkonecny@gmail.com"
copyright:           "2015-2021 Michal Konecny"

extra-source-files:
- README.md
- changelog.md

# Metadata used when publishing your package
synopsis:            Parallel computation networks using Arrow abtraction
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michalkonecny/aern2/aern2-net#readme>

dependencies:
- base == 4.*
- hspec
- QuickCheck
- transformers
- lens
- stm
- bytestring
- aeson
- collect-errors >= 0.1
- mixed-types-num >= 0.5
- aern2-mp >= 0.2

default-extensions:
- RebindableSyntax,
- PostfixOperators,
- ScopedTypeVariables,
- TypeFamilies,
- TypeOperators,
- ConstraintKinds,
- DefaultSignatures,
- MultiParamTypeClasses,
- FlexibleContexts,
- FlexibleInstances,
- UndecidableInstances,
- Arrows

other-extensions:
- TemplateHaskell

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables: 
  aern2-net-benchOp:
    main: aern2-net-benchOp.hs
    source-dirs: bench
    dependencies:
    - aern2-net
  aern2-net-simpleOp:
    main: aern2-net-simpleOp.hs
    source-dirs: bench
    dependencies:
    - aern2-net
  aern2-real-cdar-simpleOp:
    main: aern2-net-cdar-simpleOp.hs
    source-dirs: bench
    dependencies:
    - cdar

tests:
  aern2-net-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aern2-net
